services:
  app:
    build: .
    container_name: mergerr
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - next:/app/.next
    environment:
      NEXT_WEBPACK_USEPOLLING: 1
    command: npm run dev:all
    restart: always

volumes:
  next: