services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: mergerr
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./public:/app/public
    environment:
      NEXT_WEBPACK_USEPOLLING: 1
    restart: always