services:
  app:
    build: .
    container_name: mergerr
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./prisma:/app/prisma
      - next:/app/.next
    environment:
      NEXT_WEBPACK_USEPOLLING: 1
    command: yarn dev
    restart: always

volumes:
  next: