name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  packageChange:
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.changes.outputs.package }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          package:
            - './package.json'
            
  docker:
    runs-on: ubuntu-latest
    needs: packageChange
    if: ${{ needs.packageChange.outputs.package == 'true' }}
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v4
      -
        name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-mergerr:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-mergerr:${{ steps.package-version.outputs.current-version}}
